#!/bin/sh
# dfmpeg
# dmenu gui for recording your screen with ffmpeg
# Licensed under MIT, written by speedie
# https://github.com/speediegamer/dfmpeg

defaultConfig() {
	DFMPEG_DOTDIR="~/.config/dfmpeg" # The directory where dotfiles are
	DFMPEG_RESOLUTION="1920x1080" # The resolution to record in
	DFMPEG_AUDIO_DEVICE="alsa" # How to capture audio (alsa/pulseaudio)
	DFMPEG_FRAME_RATE="60" # Frame rate to capture in.
	DFMPEG_RECORD_DEVICE="x11grab" # Probably do not change.
	DFMPEG_OUTPUT_PATH="~/Videos" # Path where videos will be saved.
	DFMPEG_OUTPUT_FORMAT="mp4" # What format to use
	DFMPEG_OUTPUT_FILENAME="$DFMPEG_OUTPUT_PATH/Dfmpeg-Output-$(date +"%d-%d-%y-%T").$DFMPEG_OUTPUT_FORMAT" # File name of the output. Probably don't need to change.
	DFMPEG_WH=":0.0" # Width and height, no need to change, defaults should work.
	DFMPEG_DMENU="dmenu" # Path to dmenu
	DFMPEG_TERM="$TERMINAL" # Terminal to use when editing the configuration file.
	DFMPEG_EDITOR="vim" # Editor to edit the config file with
}

. ~/.config/dfmpeg/dfmpegrc || . "$DFMPEG_DOTDIR"/dfmpegrc || defaultConfig
startrec="ffmpeg -f $DFMPEG_RECORD_DEVICE -s $DFMPEG_RESOLUTION -i $DFMPEG_WH -f $DFMPEG_AUDIO_DEVICE -i default $DFMPEG_OUTPUT_FILENAME"
startrec_no_audio="ffmpeg -f $DFMPEG_RECORD_DEVICE -s $DFMPEG_RESOLUTION -i $DFMPEG_WH $DFMPEG_OUTPUT_FILENAME"
stoprec="pkill ffmpeg"
dfmpeg_ver="2022-04-02-r2"
about_screen="dfmpeg $dfmpeg_ver."
about_screen_2="Licensed under MIT, written by speedie + contributors."
about_screen_3="https://github.com/speediegamer/dfmpeg"

DFMPEG_CHOOSE=$(printf "Start\nStop\nStart-No-Audio\nConfigure\nExit\nAbout" | dmenu -p 'Record your screen:')

if [ "$DFMPEG_CHOOSE" = "Exit" ]; then
DFMPEG_STATUS=idle && exit 0
elif [ "$DFMPEG_CHOOSE" = "Start" ]; then
DFMPEG_STATUS=recording && $startrec && exit 0
elif [ "$DFMPEG_CHOOSE" = "Stop" ]; then
$stoprec && DFMPEG_STATUS=idle
elif [ "$DFMPEG_CHOOSE" = "Configure" ]; then
$DFMPEG_TERM $DFMPEG_EDITOR $DFMPEG_DOTDIR/dfmpegrc
elif [ "$DFMPEG_CHOOSE" = "Start-No-Audio" ]; then
DFMPEG_STATUS=recording && $startrec_no_audio && exit 0
elif [ "$DFMPEG_CHOOSE" = "About" ]; then
echo $about_screen > $DFMPEG_DOTDIR/dfmpeg_about
echo $about_screen_2 >> $DFMPEG_DOTDIR/dfmpeg_about
echo $about_screen_3 >> $DFMPEG_DOTDIR/dfmpeg_about
$DFMPEG_TERM $DFMPEG_EDITOR $DFMPEG_DOTDIR/dfmpeg_about
fi
